### ISSUE TITLE
We should deploy cadvisor and node_exporter on all nodes

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-monitoring#76]
cadvisor and node_exporter should not be in the monitoring machine but on every machine.

We should:
- rename docker-compose.filebeat to docker-compose.node
- move cadvisor and node_exporter definition in this file
- add config for each machine in prometheus

**Comment by trnl** [comment]
all hands up for that!

**Comment by alexgarel** [comment]
Yes, by the way, it's done ;-)
